name: CD

on:
  push:
    branches: [ master ]

jobs:  
  deploy-docs:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2

    - name: Install poetry
      run: pipx install poetry

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "poetry"

    - name: Install dependencies
      run: poetry install

    - name: Install sphinx hydomain
      run: poetry run pip install git+https://github.com/hylang/sphinxcontrib-hydomain.git

    - name: Build documentation
      working-directory: ./docs
      run: poetry run make html

    - name: Deploy docs to GH Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: docs/_build/html # The folder the action should deploy.
